# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from shorkin.transport.grpc import qkd_pb2 as qkd__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in qkd_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class QKDKeyExchangeStub(object):
    """QKD Key Exchange service for the classical channel portion
    of quantum key distribution over gRPC.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Initiate = channel.unary_unary(
                '/shorkin.qkd.QKDKeyExchange/Initiate',
                request_serializer=qkd__pb2.KeyExchangeInitRequest.SerializeToString,
                response_deserializer=qkd__pb2.KeyExchangeInitResponse.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/shorkin.qkd.QKDKeyExchange/GetStatus',
                request_serializer=qkd__pb2.SessionStatusRequest.SerializeToString,
                response_deserializer=qkd__pb2.SessionStatusResponse.FromString,
                _registered_method=True)


class QKDKeyExchangeServicer(object):
    """QKD Key Exchange service for the classical channel portion
    of quantum key distribution over gRPC.
    """

    def Initiate(self, request, context):
        """Initiate a new QKD key exchange session
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Query the status of a QKD session
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QKDKeyExchangeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Initiate': grpc.unary_unary_rpc_method_handler(
                    servicer.Initiate,
                    request_deserializer=qkd__pb2.KeyExchangeInitRequest.FromString,
                    response_serializer=qkd__pb2.KeyExchangeInitResponse.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=qkd__pb2.SessionStatusRequest.FromString,
                    response_serializer=qkd__pb2.SessionStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'shorkin.qkd.QKDKeyExchange', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('shorkin.qkd.QKDKeyExchange', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class QKDKeyExchange(object):
    """QKD Key Exchange service for the classical channel portion
    of quantum key distribution over gRPC.
    """

    @staticmethod
    def Initiate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shorkin.qkd.QKDKeyExchange/Initiate',
            qkd__pb2.KeyExchangeInitRequest.SerializeToString,
            qkd__pb2.KeyExchangeInitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shorkin.qkd.QKDKeyExchange/GetStatus',
            qkd__pb2.SessionStatusRequest.SerializeToString,
            qkd__pb2.SessionStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
