# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: qkd.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'qkd.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tqkd.proto\x12\x0bshorkin.qkd\"|\n\x16KeyExchangeInitRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x10\n\x08protocol\x18\x02 \x01(\t\x12\x12\n\nnum_qubits\x18\x03 \x01(\x05\x12\x17\n\x0ftarget_key_bits\x18\x04 \x01(\x05\x12\x0f\n\x07peer_id\x18\x05 \x01(\t\"f\n\x17KeyExchangeInitResponse\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x10\n\x08key_hash\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\x15\n\rerror_message\x18\x04 \x01(\t\"*\n\x14SessionStatusRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\"M\n\x15SessionStatusResponse\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x10\n\x08protocol\x18\x03 \x01(\t2\xbb\x01\n\x0eQKDKeyExchange\x12U\n\x08Initiate\x12#.shorkin.qkd.KeyExchangeInitRequest\x1a$.shorkin.qkd.KeyExchangeInitResponse\x12R\n\tGetStatus\x12!.shorkin.qkd.SessionStatusRequest\x1a\".shorkin.qkd.SessionStatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'qkd_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_KEYEXCHANGEINITREQUEST']._serialized_start=26
  _globals['_KEYEXCHANGEINITREQUEST']._serialized_end=150
  _globals['_KEYEXCHANGEINITRESPONSE']._serialized_start=152
  _globals['_KEYEXCHANGEINITRESPONSE']._serialized_end=254
  _globals['_SESSIONSTATUSREQUEST']._serialized_start=256
  _globals['_SESSIONSTATUSREQUEST']._serialized_end=298
  _globals['_SESSIONSTATUSRESPONSE']._serialized_start=300
  _globals['_SESSIONSTATUSRESPONSE']._serialized_end=377
  _globals['_QKDKEYEXCHANGE']._serialized_start=380
  _globals['_QKDKEYEXCHANGE']._serialized_end=567
# @@protoc_insertion_point(module_scope)
